baseurl = "https://plussixoneblog.com/"
DefaultContentLanguage = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#DefaultContentLanguage = "ja"
title = "plusSixOne"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "plussixone"
googleAnalytics = "UA-77406420-1"

[Params]
  subtitle = "Data driven exploration of Australian Sport"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "James Day"
  website = "plussixoneblog.com"
  email = "jamesthomasday@gmail.com"
  facebook = "plussixoneblog"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "jimmyday12"
  # gitlab = "username"
  twitter = "plusSixOneblog"
  # reddit = "username"
  linkedin = "james-day-ab648321"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1



[[menu.main]]
    identifier = "ratings"
    name = "Ratings and Predictions"
    weight = 2

[[menu.main]]
    parent = "ratings"
    name = "AFL Men's Ratings and Predictions"
    url = "page/current-afl-men-s-predictions"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 3
    
[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4
