name: Get new data and rebuild site

on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches:
      - master

jobs:
  scrape-and-commit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("fitzRoy", "tidyverse", "pacman", "here", "fst", "blogdown"))'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.66.0")'
      - name: Get data
        run: Rscript -e 'source(here::here("scripts", "weekly_data_process.R"), echo = TRUE)'
      - name: Touch files
        run: Rscript -e 'blogdown:::touch_file(here::here("content", "page", "aflm-ratings-and-simulations.Rmd"))'          
        run: Rscript -e 'blogdown:::touch_file(here::here("content", "page", "aflm-current-tips.Rmd"))'          
      - name: Build site
        run: Rscript -e 'blogdown::serve_site()'        
      - name: Commit
        run: |
          git config --global user.name 'James Day'
          git config --global user.email '17557361+jimmyday12@users.noreply.github.com'
          git add .
          git commit -m 'refreshing data and rebuilding site' || echo "No changes to commit"
          git push || echo "No changes to commit"
