name: Get new data and rebuild site

on:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  scrape-and-commit:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: Rscript -e 'install.packages(c("fitzRoy", "tidyverse", "pacman", "here", "fst"))'
      - name: Get data
        run: Rscript -e 'source(here::here("scripts", "weekly_data_process.R"), echo = TRUE)'
      - name: Commit
        run: |
          git config --global user.name 'James Day'
          git config --global user.email '17557361+jimmyday12@users.noreply.github.com'
          git add .
          git commit -m 'refreshing data and rebuilding site' || echo "No changes to commit"
          git push || echo "No changes to commit"
